In [3]:
import pandas as pd

df = pd.read_csv("Dataset1.csv")

df["Arrival_time"] = pd.to_datetime(df["Arrival_time"], format="%H:%M:%S", errors="coerce")
df["Departure_Time"] = pd.to_datetime(df["Departure_Time"], format="%H:%M:%S", errors="coerce")

In [4]:
journey_duration = df.groupby("Train_No").agg(
    Start_Time=("Arrival_time", "min"),
    End_Time=("Departure_Time", "max")
)

journey_duration["Journey_Duration_Hours"] = (
    journey_duration["End_Time"] - journey_duration["Start_Time"]
).dt.total_seconds() / 3600

journey_duration.head()

                  Start_Time            End_Time  Journey_Duration_Hours
Train_No
107      1900-01-01 00:00:00 1900-01-01 11:30:00               11.500000
108      1900-01-01 00:00:00 1900-01-01 21:28:00               21.466667
128      1900-01-01 00:34:00 1900-01-01 23:57:00               23.383333
290      1900-01-01 00:05:00 1900-01-01 22:55:00               22.833333
401      1900-01-01 01:15:00 1900-01-01 23:55:00               22.666667

In [5]:
station_traffic = df.groupby("Station_Name")["Train_No"].count()

In [6]:
station_traffic.sort_values(ascending=False).head(10)

Station_Name
CST-MUMBAI      1027
KALYAN JN        828
THANE            796
SEALDAH          745
CHENNAI BEAC     738
HOWRAH JN.       699
DADAR            598
DUM DUM JN.      463
KURLA            462
TAMBARAM         434
Name: Train_No, dtype: int64

In [7]:
station_traffic.sort_values().head(10)

Station_Name
SALEMPUR HAL    1
SATYAVALLI      1
AMAR SAHEED     1
MOTA SURKA      1
PARANUR         1
MELALATHUR      1
BANDRA          1
TENERI HALT     1
WEST CABIN T    1
VIVEKANANDA     1
Name: Train_No, dtype: int64

In [9]:
distance_duration = df.groupby("Train_No").agg(
    Total_Distance=("Distance", "max"),
    Start_Time=("Arrival_time", "min"),
    End_Time=("Departure_Time", "max")
)

distance_duration["Journey_Duration_Hours"] = (
    distance_duration["End_Time"] - distance_duration["Start_Time"]
).dt.total_seconds() / 3600

In [10]:
distance_duration[["Total_Distance", "Journey_Duration_Hours"]].corr()

                        Total_Distance  Journey_Duration_Hours
Total_Distance                1.000000                0.644531
Journey_Duration_Hours        0.644531                1.000000