In [1]:
import pandas as pd
df = pd.read_csv("Dataset1.csv")
df.head()

,SN,Train_No,Station_Code,1A,2A,3A,SL,Station_Name,Route_Number,Arrival_time,Departure_Time,Distance
0,1,107,SWV,100,100,100,100,SAWANTWADI R,1,00:00:00,10:25:00,0
1,2,107,THVM,260,228,196,164,THIVIM,1,11:06:00,11:08:00,32
2,3,107,KRMI,345,296,247,198,KARMALI,1,11:28:00,11:30:00,49
3,4,107,MAO,490,412,334,256,MADGOAN JN.,1,12:10:00,00:00:00,78
4,1,108,MAO,100,100,100,100,MADGOAN JN.,1,00:00:00,20:30:00,0

In [2]:
import pandas as pd
df = pd.read_csv("Dataset1.csv")
df.shape

(186074, 12)

In [3]:
import pandas as pd
df = pd.read_csv("Dataset1.csv")
df.columns

Index(['SN', 'Train_No', 'Station_Code', '1A', '2A', '3A', 'SL',
       'Station_Name', 'Route_Number', 'Arrival_time', 'Departure_Time',
       'Distance'],
      dtype='object')

In [4]:
train_route = df.groupby("Train_No").agg(
    Start_Station=("Station_Name", "first"),
    End_Station=("Station_Name", "last")
).reset_index()

train_route.head()

   Train_No Start_Station   End_Station
0       107  SAWANTWADI R   MADGOAN JN.
1       108   MADGOAN JN.  SAWANTWADI R
2       128   MADGOAN JN.   CHHATRAPATI
3       290  DELHI-SAFDAR  DELHI-SAFDAR
4       401    AURANGABAD  VARANASI JN.

In [5]:
df["Distance"].describe()

count    186074.000000
mean        281.353838
std         483.743964
min           0.000000
25%          23.000000
50%          73.000000
75%         291.000000
max        4260.000000
Name: Distance, dtype: float64

In [6]:
stops_per_train = df.groupby("Train_No")["Station_Code"].count()
stops_per_train.describe()

count    11113.000000
mean        16.743814
std         12.993123
min          2.000000
25%          8.000000
50%         15.000000
75%         22.000000
max        118.000000
Name: Station_Code, dtype: float64

In [10]:
df.isnull().sum()

SN                0
Train_No          0
Station_Code      0
1A                0
2A                0
3A                0
SL                0
Station_Name      0
Route_Number      0
Arrival_time      0
Departure_Time    0
Distance          0
dtype: int64

In [11]:
df[df["Distance"] < 0]

Empty DataFrame
Columns: [SN, Train_No, Station_Code, 1A, 2A, 3A, SL, Station_Name, Route_Number, Arrival_time, Departure_Time, Distance]
Index: []